#Stage-1
FROM eclipse-temurin:17-jdk AS builder

WORKDIR /app

COPY /src/Main.java /app/Main.java

COPY quotes.txt quotes.txt

javac -d /app/deps Main.java

#Stage-2

FROM gcr.io/distroless/java17-debian13

WORKDIR /app

COPY --from=builder /app/deps .

COPY --from=builder . .

EXPOSE 8000

CMD ["java","Main.java"]


